# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: 介入 | <span>Insider Urbex</span>
- content: 
bottom_saying: Insider Urbex
# Content
excerpt_link: 介入

#rss: /atom.xml

highlightjs: tomorrow-night-blue

#Works
#works:
#- works_name: AAA
#  works_url: /
#- works_name: BBB
#  works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: false

# Miscellaneous
#github: https://github.com/
#twitter: https://twitter.com/
facebook: https://www.facebook.com/insiderurbex/
#google: https://google.com/
#weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
#links:
#- name: Kieran
#  link: http://go.kieran.top/
#- name: Name
#  link: http://domain.com/